apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-capstone-web
  namespace: final-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-capstone-web
  template:
    metadata:
      labels:
        app: final-capstone-web
    spec:
      containers:
        - name: web
          image: final-capstone/web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: final-capstone-web
  namespace: final-capstone
spec:
  selector:
    app: final-capstone-web
  ports:
    - port: 80
      targetPort: 80
